package com.smart.exception;

public enum ErrorCode {
		OK,UNEXPECTED_ARGUMENT,INVALID_INTEGER,MISSING_INTEGER,MISSING_STRING,MISSING_STRING_ARR,
		INVALID_DOUBLE,MISSING_DOUBLE,INVALID_ARGUMENT_NAME,INVALID_ARGUMENT_FORMAT
}
